CI: add a GCC 16 job
This required disabling an extra compiler warning class due to picking
up issues in Bison-generated code:

  [ 18%] Building CXX object librumur/CMakeFiles/librumur.dir/parser.yy.cc.o
  /home/runner/work/rumur/rumur/build/librumur/parser.yy.cc: In member function
    ‘virtual int rumur::parser::parse()’:
  /home/runner/work/rumur/rumur/build/librumur/parser.yy.cc:1241:9: error:
    variable ‘yynerrs_’ set but not used [-Werror=unused-but-set-variable=]
   1241 |     int yynerrs_ = 0;
        |         ^~~~~~~~